"use client";

import { useState, useEffect, useRef } from "react";
import type { InboxThreadSummary, InboxThreadDetail } from "@/lib/gmail";

function formatDate(iso: string): string {
  const d = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffH = diffMs / 3_600_000;
  if (diffH < 1) return `${Math.max(1, Math.floor(diffMs / 60_000))}m ago`;
  if (diffH < 24) return `${Math.floor(diffH)}h ago`;
  if (diffH < 24 * 6) return d.toLocaleDateString(undefined, { weekday: "short" });
  if (d.getFullYear() === now.getFullYear())
    return d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  return d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
}

function formatFullDate(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    month: "short", day: "numeric", year: "numeric",
    hour: "numeric", minute: "2-digit",
  });
}

const URL_SPLIT_RE = /(https?:\/\/[^\s<>"]+)/g;

function renderLine(line: string) {
  const parts = line.split(URL_SPLIT_RE);
  return parts.map((part, i) =>
    /^https?:\/\//.test(part) ? (
      <a
        key={i}
        href={part}
        target="_blank"
        rel="noreferrer"
        className="text-primary underline underline-offset-2 break-all hover:opacity-70"
        onClick={e => e.stopPropagation()}
      >
        {part}
      </a>
    ) : (
      <span key={i}>{part}</span>
    ),
  );
}

function renderParagraphs(text: string) {
  const paragraphs = text.split(/\n{2,}/);
  return paragraphs.map((para, i) => (
    <p key={i}>
      {para.split("\n").map((line, j, arr) => (
        <span key={j}>
          {renderLine(line)}
          {j < arr.length - 1 && <br />}
        </span>
      ))}
    </p>
  ));
}

function cleanEmailText(text: string): string {
  return text
    .split("\n")
    // Remove image artifact lines generated by mail clients
    .filter(l => !/^\s*View image:\s*/i.test(l))
    .filter(l => !/^\s*Follow image link:\s*/i.test(l))
    .filter(l => !/^\s*Caption:\s*$/i.test(l))
    // Remove lines that are purely a URL
    .filter(l => !/^\s*https?:\/\/\S+\s*$/.test(l))
    // Remove decorative separator lines (---, ===, ———, mixed)
    .filter(l => !/^\s*[-=—–*_]{3,}\s*$/.test(l))
    // Convert markdown headings (### Foo) to plain text
    .map(l => l.replace(/^\s*#{1,6}\s+/, ""))
    // Convert [label](url) markdown links to just the label
    .map(l => l.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1"))
    // Strip bold/italic markers: **text**, *text*, __text__, _text_
    .map(l => l.replace(/\*\*([^*]+)\*\*/g, "$1"))
    .map(l => l.replace(/__([^_]+)__/g, "$1"))
    .map(l => l.replace(/\*([^*]+)\*/g, "$1"))
    .map(l => l.replace(/_([^_]+)_/g, "$1"))
    // Convert markdown list items (* foo or - foo) to a plain bullet
    .map(l => l.replace(/^\s*[*-]\s+/, "• "))
    // Convert bare <url> angle-bracket links to nothing
    .map(l => l.replace(/<https?:\/\/[^>]+>/g, "").trim())
    // Drop lines that became empty after stripping
    .map(l => l.trimEnd())
    .join("\n")
    // Collapse 3+ consecutive blank lines into 2
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function splitQuoted(body: string): { fresh: string; quoted: string } {
  const lines = body.split("\n");
  // Find first block of lines starting with >; everything from there on is quoted history
  let splitIdx = lines.length;
  for (let i = 0; i < lines.length; i++) {
    if (/^\s*>/.test(lines[i])) {
      // Walk back to swallow any blank line immediately before the quote block
      splitIdx = i > 0 && lines[i - 1].trim() === "" ? i - 1 : i;
      break;
    }
  }
  const fresh = lines.slice(0, splitIdx).join("\n").trimEnd();
  const quoted = lines
    .slice(splitIdx)
    .map(l => l.replace(/^\s*>+\s?/, ""))
    .join("\n")
    .trim();
  return { fresh, quoted };
}

function EmailBody({ body }: { body: string }) {
  const [showQuoted, setShowQuoted] = useState(false);
  if (!body) return <span className="text-on-surface-variant italic">(empty)</span>;

  const { fresh, quoted } = splitQuoted(cleanEmailText(body));

  return (
    <div className="text-sm text-on-surface leading-relaxed space-y-3">
      {renderParagraphs(fresh)}
      {quoted && (
        <>
          <button
            type="button"
            onClick={() => setShowQuoted(v => !v)}
            className="text-xs px-2 py-0.5 rounded border border-outline-variant/30 text-on-surface-variant hover:text-on-surface hover:border-outline-variant transition-colors"
          >
            {showQuoted ? "Hide quoted text" : "Show quoted text"}
          </button>
          {showQuoted && (
            <div className="pl-3 border-l-2 border-outline-variant/30 text-on-surface-variant space-y-3">
              {renderParagraphs(quoted)}
            </div>
          )}
        </>
      )}
    </div>
  );
}

export function InboxView({
  slug,
  artistName,
  filterKeywords = [],
  appSenderEmail = "",
}: {
  slug: string;
  artistName: string;
  filterKeywords?: string[];
  appSenderEmail?: string;
}) {
  const [threads, setThreads] = useState<InboxThreadSummary[]>([]);
  const [nextPageToken, setNextPageToken] = useState<string | null>(null);
  const [loadingThreads, setLoadingThreads] = useState(true);
  const [threadsError, setThreadsError] = useState<string | null>(null);

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<InboxThreadDetail | null>(null);
  const [loadingDetail, setLoadingDetail] = useState(false);

  const [replyBody, setReplyBody] = useState("");
  const [replySending, setReplySending] = useState(false);
  const [replyError, setReplyError] = useState<string | null>(null);
  const [replySent, setReplySent] = useState(false);
  const [replyToOverride, setReplyToOverride] = useState<string | null>(null);

  const [search, setSearch] = useState("");
  const [tattoosOnly, setTattoosOnly] = useState(false);

  const detailRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetchThreads();
  }, []);

  const fetchThreads = async (pageToken?: string) => {
    setLoadingThreads(true);
    setThreadsError(null);
    try {
      const params = pageToken ? `?pageToken=${pageToken}` : "";
      const res = await fetch(`/api/inbox${params}`);
      const data = await res.json();
      if (!res.ok) {
        if (res.status === 403) {
          setThreadsError("inbox_scope");
        } else {
          setThreadsError(data.error ?? "Failed to load inbox");
        }
        return;
      }
      setThreads(prev => pageToken ? [...prev, ...data.threads] : data.threads);
      setNextPageToken(data.nextPageToken);
    } finally {
      setLoadingThreads(false);
    }
  };

  const selectThread = async (threadId: string) => {
    if (selectedId === threadId) return;
    setSelectedId(threadId);
    setDetail(null);
    setReplyBody("");
    setReplyError(null);
    setReplySent(false);
    setReplyToOverride(null);
    setLoadingDetail(true);

    setThreads(prev =>
      prev.map(t => t.threadId === threadId ? { ...t, unread: false } : t),
    );

    try {
      const res = await fetch(`/api/inbox/${threadId}`);
      const data = await res.json();
      if (res.ok) {
        setDetail(data);
        setTimeout(() => detailRef.current?.scrollTo({ top: detailRef.current.scrollHeight, behavior: "smooth" }), 50);
      }
    } finally {
      setLoadingDetail(false);
    }
  };

  const insertBookingForm = () => {
    const origin = typeof window !== "undefined" ? window.location.origin : "";
    const url = `${origin}/${slug}/book`;
    const template =
      `Hi,\n\nThanks for reaching out! You can submit a booking inquiry through my form here:\n\n${url}\n\nLooking forward to hearing about your idea!\n\n${artistName}`;
    setReplyBody(template);
  };

  const sendReply = async () => {
    if (!detail || !replyBody.trim()) return;
    const lastMsg = detail.messages[detail.messages.length - 1];
    const to = replyToOverride ?? lastMsg.replyToEmail ?? lastMsg.fromEmail;
    const subject = detail.subject.startsWith("Re:") ? detail.subject : `Re: ${detail.subject}`;

    setReplySending(true);
    setReplyError(null);
    try {
      const res = await fetch("/api/inbox/reply", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ to, subject, body: replyBody, threadId: detail.threadId }),
      });
      if (res.ok) {
        setReplySent(true);
        setReplyBody("");
        setTimeout(() => setReplySent(false), 3000);
      } else {
        const d = await res.json();
        setReplyError(d.error ?? "Send failed");
      }
    } finally {
      setReplySending(false);
    }
  };

  const tattooKeywords = filterKeywords.map(kw => kw.toLowerCase());
  const appDomain = appSenderEmail ? appSenderEmail.split("@")[1]?.toLowerCase() : "";

  // Client-side filtering
  const q = search.toLowerCase().trim();
  const visibleThreads = threads.filter(t => {
    if (tattoosOnly && tattooKeywords.length > 0) {
      // Always show app-generated notifications (contact forms, etc.)
      const isAppSender = appDomain && t.fromEmail.toLowerCase().endsWith(`@${appDomain}`);
      if (!isAppSender) {
        const text = `${t.subject} ${t.snippet}`.toLowerCase();
        if (!tattooKeywords.some(kw => text.includes(kw))) return false;
      }
    }
    if (q) {
      return (
        t.from.toLowerCase().includes(q) ||
        t.fromEmail.toLowerCase().includes(q) ||
        t.subject.toLowerCase().includes(q) ||
        t.snippet.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const unreadCount = threads.filter(t => t.unread).length;

  return (
    <div className="flex flex-1 overflow-hidden">
      {/* Thread list */}
      <div className="w-80 shrink-0 border-r border-outline-variant/10 flex flex-col overflow-hidden">
        <div className="px-4 py-3 border-b border-outline-variant/10">
          <div className="flex items-center justify-between mb-2.5">
            <span className="text-xs font-medium text-on-surface-variant uppercase tracking-wide">
              Inbox {unreadCount > 0 && <span className="ml-1 text-primary">{unreadCount} new</span>}
            </span>
          </div>

          {/* Search */}
          <input
            type="text"
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search…"
            className="w-full px-3 py-1.5 text-sm bg-surface-container-low border border-outline-variant/30 rounded-lg focus:outline-none focus:border-primary placeholder:text-[#888888] text-on-surface"
          />

          {/* Tattoo filter toggle */}
          {filterKeywords.length > 0 && (
            <button
              type="button"
              onClick={() => setTattoosOnly(f => !f)}
              title="Only show threads matching your email template subjects"
              className={`mt-1.5 w-full text-xs px-2.5 py-1.5 rounded-lg border transition-colors text-left ${
                tattoosOnly
                  ? "bg-primary/10 border-primary/40 text-primary font-medium"
                  : "border-outline-variant/30 text-on-surface-variant hover:border-outline-variant hover:text-on-surface"
              }`}
            >
              {tattoosOnly ? "✓ Tattoo inquiries only" : "Show tattoo inquiries only"}
            </button>
          )}
        </div>

        <div className="flex-1 overflow-y-auto">
          {loadingThreads && threads.length === 0 && (
            <div className="p-6 text-sm text-on-surface-variant text-center">Loading…</div>
          )}

          {threadsError === "inbox_scope" && (
            <div className="p-5 text-sm text-on-surface-variant">
              <p className="font-medium text-on-surface mb-1">Inbox access required</p>
              <p className="mb-3">Your Google connection needs to be updated to read emails.</p>
              <a
                href="/api/auth/google/connect"
                className="inline-block px-3 py-1.5 text-sm font-medium rounded-lg bg-on-surface text-surface hover:opacity-80 transition-opacity"
              >
                Reconnect Google
              </a>
            </div>
          )}

          {threadsError && threadsError !== "inbox_scope" && (
            <div className="p-5 text-sm text-destructive">{threadsError}</div>
          )}

          {!threadsError && visibleThreads.map(thread => (
            <button
              key={thread.threadId}
              type="button"
              onClick={() => selectThread(thread.threadId)}
              className={`w-full text-left px-4 py-3.5 border-b border-outline-variant/10 transition-colors hover:bg-surface-container-high ${
                selectedId === thread.threadId ? "bg-surface-container-high" : ""
              }`}
            >
              <div className="flex items-baseline justify-between gap-2 mb-0.5">
                <span className={`text-sm truncate ${thread.unread ? "font-semibold text-on-surface" : "font-medium text-on-surface-variant"}`}>
                  {thread.from}
                </span>
                <span className="text-xs text-on-surface-variant shrink-0">{formatDate(thread.date)}</span>
              </div>
              <div className="flex items-center gap-1.5 mb-0.5">
                {thread.unread && <span className="w-1.5 h-1.5 rounded-full bg-primary shrink-0 mt-px" />}
                <span className={`text-sm truncate ${thread.unread ? "font-medium text-on-surface" : "text-on-surface-variant"}`}>
                  {thread.subject}
                </span>
              </div>
              <p className="text-xs text-on-surface-variant truncate">{thread.snippet}</p>
            </button>
          ))}

          {!threadsError && !loadingThreads && visibleThreads.length === 0 && threads.length > 0 && (
            <div className="p-6 text-sm text-on-surface-variant text-center">No matches</div>
          )}

          {nextPageToken && !loadingThreads && (
            <button
              type="button"
              onClick={() => fetchThreads(nextPageToken)}
              className="w-full py-3 text-sm text-on-surface-variant hover:text-on-surface transition-colors"
            >
              Load more
            </button>
          )}
        </div>
      </div>

      {/* Thread detail */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {!selectedId && (
          <div className="flex-1 flex items-center justify-center text-sm text-on-surface-variant">
            Select a thread to read
          </div>
        )}

        {selectedId && (
          <>
            <div ref={detailRef} className="flex-1 overflow-y-auto px-8 py-6 space-y-4">
              {loadingDetail && (
                <div className="text-sm text-on-surface-variant">Loading…</div>
              )}

              {detail && (
                <>
                  <div className="flex items-start justify-between gap-4 mb-4">
                    <h2 className="text-base font-semibold text-on-surface">{detail.subject}</h2>
                    <a
                      href={`https://mail.google.com/mail/u/0/#all/${detail.threadId}`}
                      target="_blank"
                      rel="noreferrer"
                      className="shrink-0 text-xs px-2.5 py-1 rounded-md border border-outline-variant/30 text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface transition-colors whitespace-nowrap"
                    >
                      Open in Gmail ↗
                    </a>
                  </div>

                  {detail.messages.map((msg) => (
                    <div
                      key={msg.messageId}
                      className={`rounded-xl border p-5 space-y-3 ${
                        msg.unread
                          ? "border-primary/20 bg-primary/3"
                          : "border-outline-variant/20 bg-surface-container-lowest"
                      }`}
                    >
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <span className="text-sm font-semibold text-on-surface">{msg.from}</span>
                          <span className="text-xs text-on-surface-variant ml-2">&lt;{msg.fromEmail}&gt;</span>
                        </div>
                        <span className="text-xs text-on-surface-variant shrink-0">{formatFullDate(msg.date)}</span>
                      </div>
                      {msg.to && (
                        <p className="text-xs text-on-surface-variant">To: {msg.to}</p>
                      )}
                      <EmailBody body={msg.body} />
                    </div>
                  ))}
                </>
              )}
            </div>

            {/* Reply area */}
            {detail && (() => {
              const lastMsg = detail.messages[detail.messages.length - 1];
              const autoTo = lastMsg?.replyToEmail ?? lastMsg?.fromEmail ?? "";
              const altTo = lastMsg?.replyToEmail && lastMsg.fromEmail !== lastMsg.replyToEmail ? lastMsg.fromEmail : null;
              const effectiveTo = replyToOverride ?? autoTo;
              return (
              <div className="border-t border-outline-variant/10 px-8 py-5 space-y-3 bg-surface shrink-0">
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2 min-w-0">
                    <p className="text-xs font-medium text-on-surface-variant uppercase tracking-wide shrink-0">To:</p>
                    {altTo ? (
                      <select
                        value={effectiveTo}
                        onChange={e => setReplyToOverride(e.target.value)}
                        className="text-xs text-on-surface bg-surface-container-low border border-outline-variant/30 rounded px-2 py-1 focus:outline-none focus:border-primary max-w-[260px] truncate"
                      >
                        <option value={autoTo}>{autoTo}</option>
                        <option value={altTo}>{altTo}</option>
                      </select>
                    ) : (
                      <span className="text-xs text-on-surface truncate">{effectiveTo}</span>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={insertBookingForm}
                    className="text-xs px-2.5 py-1 rounded-md border border-outline-variant/30 text-on-surface-variant hover:bg-surface-container-high hover:text-on-surface transition-colors shrink-0"
                  >
                    + Insert booking form link
                  </button>
                </div>
                <textarea
                  value={replyBody}
                  onChange={e => setReplyBody(e.target.value)}
                  rows={5}
                  placeholder="Write a reply…"
                  className="w-full px-3 py-2.5 text-sm text-on-surface bg-surface-container-low border border-outline-variant/30 rounded-lg focus:outline-none focus:border-primary resize-none placeholder:text-[#888888]"
                />
                <div className="flex items-center gap-3">
                  <button
                    type="button"
                    onClick={sendReply}
                    disabled={replySending || !replyBody.trim()}
                    className="px-4 py-2 text-sm font-medium rounded-lg bg-on-surface text-surface hover:opacity-80 transition-opacity disabled:opacity-40"
                  >
                    {replySending ? "Sending…" : "Send reply"}
                  </button>
                  {replySent && (
                    <span className="text-sm text-emerald-600">Sent!</span>
                  )}
                  {replyError && (
                    <span className="text-sm text-destructive">{replyError}</span>
                  )}
                </div>
              </div>
              );
            })()}
          </>
        )}
      </div>
    </div>
  );
}
